
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  hello:    
    runs-on : ubuntu-latest
    steps:
      - name: 24f1000656@ds.study.iitm.ac.in
        run: echo "Hello, world!"
      
